# Generated by Django 3.2.5 on 2021-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('materialinterno', models.CharField(max_length=15)),
                ('materialsola', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=20)),
                ('ocasiao', models.CharField(max_length=50)),
                ('tamanho', models.IntegerField()),
            ],
        ),
    ]
