# Generated by Django 3.2.5 on 2021-07-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roupas',
            new_name='Calcados',
        ),
    ]
